# -*- coding: utf-8 -*-
"""ChangeDate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-FrkCAM3MlJ4mZTqAOMuV4EMtiM0QZqB
"""

import pandas as pd
def CambiarFechas():
  year_row = pd.Series([])
  month_row = pd.Series([])
  df_Base_Datos = pd.read_excel("dataset_tasacion_train_vf.xlsx")
  #print(df_Base_Datos["Fecha entrega del Informe"])
  for i in range(df_Base_Datos.shape[0]):
    #print(df_Base_Datos["Fecha entrega del Informe"])
    string= str(df_Base_Datos["Fecha entrega del Informe"][i]).split("-")
    year_row[i]=string[0]+"/ "+string[1]
  df_Base_Datos.insert(1,"Año/Mes", year_row)
  df_Base_Datos = df_Base_Datos.drop(labels="Fecha entrega del Informe", axis=1)
  df_Base_Datos.to_csv('Archivo_año_mes.csv', header = True, encoding="latin-1")
CambiarFechas()

