# -*- coding: utf-8 -*-
"""GuardarDelitos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TrA4x-f2p9j1bnwnUCO18eatPca-hhy_
"""

import pandas as pd
def _Agregar_Delitos():
  df_Base_Datos = pd.read_csv("Estadistica_NumDelitosPorDepartamento.csv", encoding="latin-1")
  df_Base_Datos2 = pd.read_csv("PreFinal1.csv", encoding="latin-1")
  print(df_Base_Datos2.head(5))
  Delitos_row = pd.Series([])
  for i in range(df_Base_Datos2.shape[0]):
    line = df_Base_Datos.loc[df_Base_Datos2["Departamento"][i]==df_Base_Datos["Departamento"]]
    hola = str(line["2021"]).split("   ")
    try: 
      Delitos_row[i]=hola[1]
    except:
      Delitos_row[i]=hola[0]
    #print(line)
  df_Base_Datos2.insert(4,"Delitos", Delitos_row)
  df_Base_Datos2.to_csv('Delitos.csv', header = True, encoding="latin-1")
_Agregar_Delitos()

