# -*- coding: utf-8 -*-
"""InsertColumn_Final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ttDbz9x2ZuGIFeCe87FRPF3LyQuCNEr-
"""

pip install Unidecode

import pandas as pd
from unidecode import unidecode
def _get_Ubigeo(Departamento, Provincia, Distrito):
  Departamento1=unidecode(Departamento).replace(" Y "," y ")
  Provincia1=unidecode(Provincia).replace(" Y "," y ")
  Distrito1=unidecode(Distrito).replace(" Y "," y ")
  Departamento2 =Departamento.capitalize()
  Provincia2 =Provincia.capitalize()
  Distrito2 = Distrito.capitalize()
  #print(Distrito)
  df = pd.read_csv("geodir-ubigeo-inei.csv",encoding = 'latin-1')
  df2 = pd.read_csv("Ubigeo-ID-Descripción.csv",encoding = 'latin-1')
  if(Provincia == "Chincha" and Distrito == "Chincha"):
    return 110201
  
  try: 
    solucion = df.loc[(df['Departamento']==Departamento1)&(df['Provincia']==Provincia1)&(df['Distrito']==Distrito1)]
    return int(solucion["Ubigeo"])
  except:
    try:
      print(Provincia2)
      #print(df2.loc[df2['Distrito']==Distrito2])
      solucion = df2.loc[(df2['Departamento']==Departamento)& (df2['Distrito']==Distrito)] 
      #print(df2.loc[(df2['Departamento']==Departamento)])
      return int(solucion["Ubigeo"])
    except:
      try:
        solucion = df2.loc[(df2['Provincia']==Provincia)& (df2['Distrito']==Distrito)]
      #print(df2.loc[(df2['Departamento']==Departamento)& (df2['Distrito']==Distrito)])
        return int(solucion["Ubigeo"])
      except:
        try:
          solucion = df2.loc[(df2['Departamento']==Departamento1)& (df2['Distrito']==Distrito1)]
          return int(solucion["Ubigeo"]) 
        except:
            try:
              solucion = df2.loc[ df2['Distrito']==Distrito]
              return int(solucion["Ubigeo"])
            except:
              try:
                solucion = df2.loc[ df2['Distrito']==Distrito2]
                return int(solucion["Ubigeo"])
              except:
                try: 
                  solucion = df2.loc[(df2['Departamento']==Departamento1 + " ")& (df2['Distrito']==Distrito1)]
                  return int(solucion["Ubigeo"])
                except:
                  return 0
#_get_Ubigeo("Amazonas", "Chachapoyas", "Chachapoyas")

import pandas as pd


  #hace un diccionario y lo agrega
def _insert_Ubigeo_():
  #Aquí cambiar el nombre al de la base de datos
  ubigeo_row = pd.Series([])  
  df_Base_Datos = pd.read_excel("dataset_tasacion_train_vf.xlsx")
  for i in range(df_Base_Datos.shape[0]):
    ubigeo_row[i]=_get_Ubigeo(str(df_Base_Datos['Departamento'][i]),str(df_Base_Datos['Provincia'][i]),str(df_Base_Datos['Distrito'][i]))

  df_Base_Datos.insert(6,"Ubigeo", ubigeo_row)
  df_Base_Datos.to_csv('PreFinal.csv', header = True, encoding = 'latin-1')

_insert_Ubigeo_()

_get_Ubigeo("San Martín", "ALTO AMAZONAS", "ALTO AMAZONAS")

