# -*- coding: utf-8 -*-
"""ObtenerHileraEnaho.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Otd43OS2wuO7L70MTDoNeg2-1fb8Ud8B
"""

import pandas as pd
def _Obtener_Hilera(nombre_Fila):
  Fila = {}
  DataSet = pd.read_csv("Enaho01-2022-100.csv",encoding='latin-1')
  for i in range(DataSet.shape[0]):
    try:
      Fila[str(DataSet["UBIGEO"][i])]=str(DataSet[nombre_Fila][i])
    except:
      print("Poner otro nombre de fila.")
  return Fila

def _Agregar_Hilera(nombre_Hilera):
  Hilera_row= pd.Series([])
  diccionario = _Obtener_Hilera(nombre_Hilera)
  df_Base_Datos = pd.read_csv("DataArchive.csv",encoding='latin-1')
  for i in range(df_Base_Datos.shape[0]):
    Hilera_row[i]=diccionario[df_Base_Datos.iloc[i][6]]
  df_Base_Datos.insert(7,nombre_Hilera, Hilera_row)
  df_Base_Datos.to_csv('Final.csv', header = True, )